server:
  port: 7001
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false    #是否将自己注册到eureka中
    fetch-registry: false   #是否从eureka中获取信息
    service-url:            # 配置的是其他客户端，需要连接eureka或者说注册到eureka时，路径应该这样写      defaultZone: http://127.0.0.1:7001/eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
